<?php

return [
    'promotional_text' => "Hey :firstName, you've got a message from :businessName at SpotBie: :body. Reply with \"STOP\" to opt-out of SMS, \"HELP\" for more info",
    'smsOptInText' => "Hey :firstName, this is SpotBie! You've opted-in to promotional text messages by providing your phone number in your account settings. Reply with \"STOP\" to opt-out of SMS, \"HELP\" for more info. Msg. frequency varies. Msg and data rates may apply. You can view our privacy, terms & conditions here: https://spotbie.com/terms",
    'accountCreatedSmsOptInText' => "Hey :firstName, this is SpotBie! You've created an account with us and opted-in to promotional text messages by providing your phone number at :businessName. Check your e-mail to set your password. Reply with \"STOP\" to opt-out of SMS, \"HELP\" for more info. Msg. frequency varies. Msg and data rates may apply. You can view our privacy, terms & conditions here: https://spotbie.com/terms",
    'accountCompletionReminderText' => "Hello :firstName! You recently created a SpotBie account at :businessName but didn't finish setting your password. You can finish doing so by requesting a password reset link here: https://home.spotbie.com/forgot-password Log-in to SpotBie and see what :businessName has for rewards… stack enough points and you’ll be able to redeem from the store! Go shop at :businessName for more points, check out their SpotBie portal :portalUrl",
    'rewardRedeemedTextWithEmail' => "Hey :firstName, this is SpotBie! You've redeemed :rewardName from :businessName. Log-in at https://spotbie.com/ to see more. Reply with \"STOP\" to opt-out of SMS, \"HELP\" for more info.",
    'rewardRedeemedText' => "Hey :firstName, this is SpotBie! You've redeemed :rewardName from :businessName. Reply with \"STOP\" to opt-out of SMS, \"HELP\" for more info.",
    'passwordResetText' => "Hello :firstName, you have requested a password reset link from SpotBie: https://spotbie.com/password/reset/:token If this was not you, please contact us at admin@spotbie.com",
    'pointsRedeemedTextWithEmail' => "Hey :firstName, this is SpotBie! You've redeemed :businessPoints + :bonusPoints (bonus) for a total of :totalPoints loyalty points from :businessName. Log-in at https://spotbie.com/ to see more. Reply with \"STOP\" to opt-out of SMS, \"HELP\" for more info.",
    'pointsBonusText' =>  "Hey :firstName, this is SpotBie! You have signed-up to go visit :businessName on a :dayOfWeek from :range1 to :range2 :range3. Otherwise, go at whatever time you like and ask for SpotBie Loyalty Points when it's time to pay the bill. If your account is new, you'll need to follow the instructions on the e-mail. Reply with \"STOP\" to opt-out of SMS, \"HELP\" for more info.",
    'inviteContact' =>  "Hey :displayName, this is SpotBie! :personInviting has invited you to use the app. You'll gain loyalty points, attend meet-ups at restaurants and events, plus get to contribute and explore an amazing community. Visit https://home.spotbie.com/ for more! Reply with \"STOP\" to opt-out of SMS, \"HELP\" for more info.",
    'invitationSmsText' =>  "Hey :guestName, this is SpotBie! :hostName has invited you to \":meetUpName\" at :businessName on :date. Here's a list of who is invited; :invitationListNameList. Confirm you're going by tapping here https://spotbie.com/accept-invitation/:invitationId. Reply with \"STOP\" to opt-out of SMS, \"HELP\" for more info.",
];
